# Generated by Django 4.2.11 on 2026-06-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_ratingmedia_mediareport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmedia',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('removed', 'Removed'), ('failed', 'Failed')], default='processing', max_length=10),
        ),
    ]
