# Generated by Django 4.2.11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_ratingreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaReport',
        ),
    ]
