# Generated by Django 4.2.11 on 2026-06-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_delete_mediareport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='has_cover',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
