# Generated by Django 4.2.11 on 2026-05-30 02:22

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('address', models.TextField()),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('timezone', models.CharField(default='America/Chicago', max_length=50)),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('price_level', models.IntegerField(blank=True, choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')], null=True)),
                ('music_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('crowd_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('typical_cover', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_venues', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='cities.city')),
            ],
            options={
                'ordering': ['-overall_rating', 'name'],
                'unique_together': {('city', 'slug')},
            },
        ),
    ]
