# Generated by Django 4.2.11 on 2026-06-07 19:01

import math
from django.db import migrations, models
from django.db.models import F


def backfill_price(apps, schema_editor):
    """Seed `google_price_level` from the current `price_level` (which until now
    held Google's value), then recompute the displayed price for venues that
    already have rated prices — treating Google as one vote, halves rounding down.
    """
    Venue = apps.get_model("venues", "Venue")
    Rating = apps.get_model("ratings", "Rating")

    # 1. Every venue's existing price_level *is* its Google value today.
    Venue.objects.update(google_price_level=F("price_level"))

    # 2. Re-derive the displayed price wherever users have already submitted one.
    rated = Venue.objects.filter(ratings__price_level__isnull=False).distinct()
    for venue in rated:
        votes = list(
            Rating.objects.filter(venue=venue, price_level__isnull=False)
            .values_list("price_level", flat=True)
        )
        if venue.google_price_level is not None:
            votes.append(venue.google_price_level)
        if votes:
            venue.price_level = math.ceil(sum(votes) / len(votes) - 0.5)
            venue.save(update_fields=["price_level"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venuerequest'),
        ('ratings', '0006_delete_mediareport'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='google_price_level',
            field=models.IntegerField(blank=True, choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')], null=True),
        ),
        migrations.RunPython(backfill_price, noop),
    ]
