# Generated by Django 4.2.11 on 2026-06-04 17:41

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_enable_trigram'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='city',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='city_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['-venue_count'], name='city_venue_count_idx'),
        ),
    ]
