# Generated by Django 4.2.11 on 2026-06-02 19:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('removed', 'Removed'), ('failed', 'Failed')], default='processing', max_length=10)),
                ('original_key', models.CharField(max_length=512)),
                ('thumbnail_key', models.CharField(blank=True, max_length=512)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='chat.venuemessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
