# Generated by Django 4.2.11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_venuemessagereport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageMediaReport',
        ),
    ]
