# Generated by Django 4.2.11 on 2026-06-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_delete_messagemediareport'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venuemessage',
            index=models.Index(fields=['venue', 'created_at'], name='chat_venuem_venue_i_c28b52_idx'),
        ),
    ]
