# Generated by Django 4.2.11 on 2026-06-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['venue', 'expires_at'], name='checkins_ch_venue_i_878e20_idx'),
        ),
    ]
